name = "Hello-Keyword"
badges = ["github-actions/test.yml"]
static_install = "auto"
module_maker = "ModuleBuild"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ["t", "xt", "tool", "author", "example", "benchmarks", "builder"]
